import { Action, SubTask, VerifierSubtaskResult, WorkbookContext } from '../types/agent.types';

export const VERIFIER_SYSTEM_PROMPT = `
You are the Verifier agent for Cellix, an Excel AI assistant.

Your job:
- Review actions generated by the Executor, grouped by subtask
- Check they correctly fulfil the original user prompt
- Flag errors or data-loss risks per subtask
- Return ONLY valid JSON

Output schema:
{
  "passed": true,
  "feedback": "All actions correctly implement the request",
  "issues": [],
  "subtaskResults": [
    {
      "subtaskId": "s1",
      "passed": true,
      "feedback": "Subtask actions look correct",
      "issues": []
    }
  ]
}

Or on failure:
{
  "passed": false,
  "feedback": "Row index is off by one in subtask s2",
  "issues": [
    {
      "severity": "error",
      "subtaskId": "s2",
      "actionIndex": 0,
      "description": "ADD_ROW targets wrong position relative to user request",
      "suggestion": "Adjust row placement to match user intent"
    }
  ],
  "subtaskResults": [
    {
      "subtaskId": "s1",
      "passed": true,
      "feedback": "OK",
      "issues": []
    },
    {
      "subtaskId": "s2",
      "passed": false,
      "feedback": "Row index is off by one",
      "issues": [
        {
          "severity": "error",
          "actionIndex": 0,
          "description": "ADD_ROW targets wrong position",
          "suggestion": "Adjust row placement"
        }
      ]
    }
  ]
}

Rules:
- severity "error" = action must not be applied as-is
- severity "warning" = likely ok but flag for user
- Evaluate EACH subtask independently in subtaskResults
- passed (top-level) is true only if ALL subtaskResults passed
- Syntax, reference bounds, and named-range checks are ALREADY handled by the deterministic formula validator — do NOT re-check those
- Focus on SEMANTIC correctness: does each formula/action actually answer the user's intent?
- Check: correct sheet, correct row/column placement for the task, no accidental overwrites of unrelated data
- Actions use 0-based row/col (row 0 = Excel row 1)
- If actions are empty and the task was non-trivial, that is an error
- Do not invent new actions — only review what was provided
`;

export function buildVerifierUserMessage(
  originalPrompt: string,
  subtasks: SubTask[],
  actionsBySubtask: Record<string, Action[]>,
  context: WorkbookContext,
  formulaValidatorSummary?: string,
): string {
  const activeSheet = context.sheets.find((s) => s.name === context.activeSheetName);

  const grouped = subtasks.map((st) => ({
    subtaskId: st.id,
    description: st.description,
    targetSheet: st.targetSheet,
    actions: actionsBySubtask[st.id] ?? [],
  }));

  return `
Original user prompt: "${originalPrompt}"

Deterministic formula validator (syntax + references already checked):
${formulaValidatorSummary ?? 'No validator summary available.'}

Subtasks and their proposed actions:
${JSON.stringify(grouped, null, 2)}

Workbook context (active sheet, first 10 rows):
${JSON.stringify(activeSheet?.values.slice(0, 10))}

Return JSON only. Focus on semantic correctness — syntax is already validated.
`;
}

/** Normalize verifier LLM output — ensure subtaskResults exists and top-level passed is consistent. */
export function normalizeVerifierOutput(
  parsed: Partial<{
    passed: boolean;
    feedback: string;
    issues: VerifierSubtaskResult['issues'];
    subtaskResults: VerifierSubtaskResult[];
  }>,
  subtaskIds: string[],
): {
  passed: boolean;
  feedback: string;
  issues: VerifierSubtaskResult['issues'];
  subtaskResults: VerifierSubtaskResult[];
} {
  const subtaskResults: VerifierSubtaskResult[] = Array.isArray(parsed.subtaskResults)
    ? parsed.subtaskResults.map((r) => ({
        subtaskId: String(r.subtaskId),
        passed: Boolean(r.passed),
        feedback: String(r.feedback ?? ''),
        issues: Array.isArray(r.issues) ? r.issues : [],
      }))
    : [];

  for (const id of subtaskIds) {
    if (!subtaskResults.some((r) => r.subtaskId === id)) {
      subtaskResults.push({
        subtaskId: id,
        passed: Boolean(parsed.passed),
        feedback: String(parsed.feedback ?? ''),
        issues: [],
      });
    }
  }

  const passed =
    subtaskResults.length > 0
      ? subtaskResults.every((r) => r.passed)
      : Boolean(parsed.passed);

  const issues =
    Array.isArray(parsed.issues) && parsed.issues.length > 0
      ? parsed.issues
      : subtaskResults.flatMap((r) =>
          r.issues.map((issue) => ({ ...issue, subtaskId: issue.subtaskId ?? r.subtaskId })),
        );

  return {
    passed,
    feedback: String(parsed.feedback ?? ''),
    issues,
    subtaskResults,
  };
}
